version: "3.1"

services:
  front-dev:
    image: node:18.2.0
    container_name: trivia-front-dev
    command: bash -c "npm install && npm run dev -- --host"
    # user: "$(id -u):$(id -g)"
    working_dir: /opt/front
    volumes:
      - ./trivia:/opt/front
    
    ports:
      - "5173:5173"

